# Generated by Django 5.2 on 2025-05-05 20:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id_bus', models.BigAutoField(primary_key=True, serialize=False)),
                ('placa', models.TextField(unique=True)),
                ('marca', models.TextField(blank=True, null=True)),
                ('modelo', models.TextField(blank=True, null=True)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Mantenimiento', 'Mantenimiento'), ('Inactivo', 'Inactivo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('estado', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateField()),
                ('monto_inicial', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion_legal', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('duracion_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timbrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_timbrado', models.CharField(max_length=15, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField()),
                ('requiere_cliente_registrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id_asiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_asiento', models.IntegerField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado'), ('Ocupado', 'Ocupado')], default='Disponible', max_length=20)),
                ('tipo_asiento', models.CharField(blank=True, choices=[('Ejecutivo', 'Ejecutivo'), ('Semi-cama', 'Semi-cama'), ('Cama', 'Cama')], max_length=20, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.bus')),
            ],
            options={
                'unique_together': {('bus', 'numero_asiento')},
            },
        ),
        migrations.CreateModel(
            name='CabeceraCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mov', models.CharField(max_length=20)),
                ('fecha_mov', models.DateTimeField()),
                ('monto_inical', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.caja')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('dv', models.CharField(blank=True, max_length=2, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CabeceraFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.TextField(unique=True)),
                ('fecha_factura', models.DateField(default=django.utils.timezone.now)),
                ('condicion', models.CharField(default='Contado', max_length=30)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_exenta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_iva_10', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_iva_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr4cking_rest_api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_transaccion', models.CharField(max_length=50)),
                ('monto', models.IntegerField()),
                ('fecha_transaccion', models.DateTimeField()),
                ('cabecera_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.cabeceracaja')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr4cking_rest_api.cabecerafactura')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_contratacion', models.DateField()),
                ('cargo', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='cabecerafactura',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.empleado'),
        ),
        migrations.AddField(
            model_name='cabeceracaja',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.empleado'),
        ),
        migrations.AddField(
            model_name='bus',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.empresa'),
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id_encomienda', models.BigAutoField(primary_key=True, serialize=False)),
                ('flete', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.cliente')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino_encomienda', to='tr4cking_rest_api.detalleruta')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen_encomienda', to='tr4cking_rest_api.detalleruta')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('campo_modificado', models.CharField(max_length=30)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.empleado')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.cabecerafactura')),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id_parada', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_parada', models.CharField(choices=[('A', 'Agencia'), ('P', 'Parada de Bus'), ('T', 'Terminal')], max_length=1)),
                ('nombre', models.TextField(unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.empresa')),
                ('localidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.localidad')),
            ],
        ),
        migrations.AddField(
            model_name='detalleruta',
            name='parada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.parada'),
        ),
        migrations.AddField(
            model_name='cabecerafactura',
            name='parada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.parada'),
        ),
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id_pasaje', models.BigAutoField(primary_key=True, serialize=False)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.asiento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('iva_porcentaje', models.SmallIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.cabecerafactura')),
                ('encomienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr4cking_rest_api.encomienda')),
                ('pasaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr4cking_rest_api.pasaje')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hora_salida', models.TimeField()),
                ('dias_semana', models.CharField(max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.ruta')),
            ],
            options={
                'unique_together': {('ruta', 'hora_salida')},
            },
        ),
        migrations.AddField(
            model_name='detalleruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.ruta'),
        ),
        migrations.AddField(
            model_name='cabecerafactura',
            name='timbrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.timbrado'),
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.bus')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.horario')),
            ],
            options={
                'unique_together': {('bus', 'fecha', 'horario')},
            },
        ),
        migrations.AddField(
            model_name='pasaje',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.viaje'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.viaje'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleruta',
            unique_together={('ruta', 'orden'), ('ruta', 'parada')},
        ),
    ]
