# Generated by Django 5.2 on 2025-05-27 01:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id_bus', models.BigAutoField(primary_key=True, serialize=False)),
                ('placa', models.TextField(unique=True)),
                ('marca', models.TextField(blank=True, null=True)),
                ('modelo', models.TextField(blank=True, null=True)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Mantenimiento', 'Mantenimiento'), ('Inactivo', 'Inactivo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('estado', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateField()),
                ('monto_inicial', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('dv', models.CharField(blank=True, help_text='Dígito verificador (opcional)', max_length=2, null=True)),
                ('razon_social', models.CharField(help_text='Para facturación, prioridad: auth_user > cliente o empleado para casuales', max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.BigAutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion_legal', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('coordenadas', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id_pasajero', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.TextField(help_text='Requerido para facturación')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timbrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_timbrado', models.CharField(max_length=15, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField()),
                ('requiere_cliente_registrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id_asiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_asiento', models.IntegerField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado'), ('Ocupado', 'Ocupado')], default='Disponible', max_length=20)),
                ('tipo_asiento', models.CharField(blank=True, choices=[('Semi-cama', 'Semi-cama'), ('Cama', 'Cama')], max_length=20, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.bus')),
            ],
            options={
                'unique_together': {('bus', 'numero_asiento')},
            },
        ),
        migrations.CreateModel(
            name='CabeceraCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mov', models.CharField(max_length=20)),
                ('fecha_mov', models.DateTimeField()),
                ('monto_inical', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.caja')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='CabeceraFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.TextField(unique=True)),
                ('fecha_factura', models.DateField(default=django.utils.timezone.now)),
                ('condicion', models.CharField(default='Contado', max_length=30)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_exenta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_iva_10', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_iva_5', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr4cking_rest_api.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_transaccion', models.CharField(max_length=50)),
                ('monto', models.IntegerField()),
                ('fecha_transaccion', models.DateTimeField()),
                ('cabecera_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.cabeceracaja')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr4cking_rest_api.cabecerafactura')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.empresa'),
        ),
        migrations.AddField(
            model_name='bus',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.empresa'),
        ),
        migrations.CreateModel(
            name='HistorialFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('campo_modificado', models.CharField(max_length=30)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.empleado')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.cabecerafactura')),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id_parada', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('coordenadas', models.FloatField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.localidad')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
            },
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id_encomienda', models.BigAutoField(primary_key=True, serialize=False)),
                ('flete', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remitente', models.CharField(max_length=100)),
                ('ruc_ci', models.CharField(max_length=20)),
                ('numero_contacto', models.CharField(max_length=20)),
                ('tipo_envio', models.CharField(choices=[('sobre', 'Sobre'), ('paquete', 'Paquete'), ('ambos', 'Ambos')], max_length=10)),
                ('cantidad_sobre', models.PositiveIntegerField(default=0)),
                ('cantidad_paquete', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.cliente')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino_encomienda', to='tr4cking_rest_api.parada')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen_encomienda', to='tr4cking_rest_api.parada')),
            ],
        ),
        migrations.AddField(
            model_name='cabecerafactura',
            name='parada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.parada'),
        ),
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id_pasaje', models.BigAutoField(primary_key=True, serialize=False)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.asiento')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('iva_porcentaje', models.SmallIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.cabecerafactura')),
                ('encomienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr4cking_rest_api.encomienda')),
                ('pasaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr4cking_rest_api.pasaje')),
            ],
        ),
        migrations.AddField(
            model_name='pasajero',
            name='cedula',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.persona'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cedula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr4cking_rest_api.persona'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cedula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr4cking_rest_api.persona'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Pagada', 'Pagada'), ('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='pasaje',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.reserva'),
        ),
        migrations.AddField(
            model_name='cabecerafactura',
            name='timbrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.timbrado'),
        ),
        migrations.CreateModel(
            name='UsuarioPersona',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cedula', models.OneToOneField(db_column='cedula', on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.persona')),
            ],
            options={
                'db_table': 'usuario_persona',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.bus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.ruta')),
            ],
            options={
                'unique_together': {('bus', 'fecha')},
            },
        ),
        migrations.AddField(
            model_name='pasaje',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.viaje'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.viaje'),
        ),
        migrations.CreateModel(
            name='DetalleRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('orden', models.IntegerField()),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.parada')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.ruta')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('ruta', 'parada')},
            },
        ),
    ]
