# Generated by Django 5.2 on 2025-04-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr4cking_rest_api', '0002_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='detalles',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
